# Adds the `analyseJenkins` command to your PowerShell profile. Runnable
# from any directory — the script locates the project itself. Re-run
# only if the project moves; the script no-ops if the same registration
# already exists.
#
# Usage:
#   & 'C:\path\to\Jenkins\scripts\setup.ps1'
#   . $PROFILE              # reload profile
#   analyseJenkins           # now works from anywhere

$ErrorActionPreference = "Stop"

# Find the project root from the script's own location.
# $PSScriptRoot is the script's directory regardless of how it was invoked.
$ScriptDir  = $PSScriptRoot
$ProjectDir = (Resolve-Path (Join-Path $ScriptDir "..")).Path

# Confirm we're actually pointed at the project root.
if (-not (Test-Path (Join-Path $ProjectDir "app.py")) -or `
    -not (Test-Path (Join-Path $ProjectDir "config\rules"))) {
    Write-Host "ERROR: '$ProjectDir' does not look like the Jenkins dashboard project root."
    Write-Host "       Expected: app.py and config\rules\ at this location."
    Write-Host "       Make sure scripts\setup.ps1 lives inside the project's scripts\ folder."
    exit 1
}

# Make sure the user's PowerShell profile exists before we read or write it.
if (-not (Test-Path -Path $PROFILE)) {
    New-Item -ItemType File -Path $PROFILE -Force | Out-Null
}

$BeginMark = "# >>> analyseJenkins (managed by scripts\setup.ps1) >>>"
$EndMark   = "# <<< analyseJenkins (managed by scripts\setup.ps1) <<<"

$existing  = Get-Content -Path $PROFILE -Raw -ErrorAction SilentlyContinue
if ($null -eq $existing) { $existing = "" }

# Skip if the same registration is already in place. Pulls the Push-Location
# path out of any existing block and compares it to the current project root.
$ExistingDir = ""
$blockPattern = [regex]::Escape($BeginMark) + "(?s)(.*?)" + [regex]::Escape($EndMark)
$blockMatch   = [regex]::Match($existing, $blockPattern)
if ($blockMatch.Success) {
    $bodyText    = $blockMatch.Groups[1].Value
    $pushMatch   = [regex]::Match($bodyText, 'Push-Location\s+"([^"]+)"')
    if ($pushMatch.Success) { $ExistingDir = $pushMatch.Groups[1].Value }
}
if ($ExistingDir -ne "" -and $ExistingDir -eq $ProjectDir) {
    Write-Host "OK  analyseJenkins already registered for this project — nothing to do."
    Write-Host "    Project: $ProjectDir"
    Write-Host "    Profile: $PROFILE"
    exit 0
}

# Function body written into the profile. ProjectDir is captured here so
# the command keeps working from any directory. 
$Block = @"
$BeginMark
# Auto-generated by $ProjectDir\scripts\setup.ps1
# Re-run scripts\setup.ps1 whenever you move or re-clone the project.
function analyseJenkins {
    Push-Location "$ProjectDir"
    try {
        # Pick the first venv directory that exists.
        `$venvDir = `$null
        foreach (`$candidate in @('venv', '.venv', 'env')) {
            if (Test-Path (Join-Path `$candidate 'Scripts\Activate.ps1')) {
                `$venvDir = `$candidate; break
            }
        }
        if (-not `$venvDir) {
            Write-Host "venv missing — run: py -3 -m venv venv; .\venv\Scripts\Activate.ps1; pip install Flask requests PyYAML"
            return
        }
        & (Join-Path `$venvDir 'Scripts\Activate.ps1')
        # Use whichever Python is on PATH after activation.
        `$pyCmd = if (Get-Command python -ErrorAction SilentlyContinue) { 'python' }
                  elseif (Get-Command py -ErrorAction SilentlyContinue) { 'py' }
                  else { Write-Host "No Python on PATH after activating `$venvDir"; return }
        & `$pyCmd app.py
    }
    finally {
        Pop-Location
    }
}
$EndMark
"@

# Safe to re-run: strip any previous block with our marker before appending.
$cleaned = [regex]::Replace($existing, $blockPattern, "")

# Also clean up the older marker from before the scripts\ folder existed.
$legacyBegin   = "# >>> analyseJenkins (managed by setup.ps1) >>>"
$legacyEnd     = "# <<< analyseJenkins (managed by setup.ps1) <<<"
$legacyPattern = [regex]::Escape($legacyBegin) + "(?s).*?" + [regex]::Escape($legacyEnd)
$cleaned       = [regex]::Replace($cleaned, $legacyPattern, "")

$trimmed = $cleaned.TrimEnd()
if ($trimmed.Length -gt 0) {
    $final = $trimmed + "`r`n`r`n" + $Block + "`r`n"
} else {
    $final = $Block + "`r`n"
}

Set-Content -Path $PROFILE -Value $final -Encoding UTF8

if ($ExistingDir -ne "") {
    Write-Host "OK  analyseJenkins re-registered (project moved)."
    Write-Host "    Old project: $ExistingDir"
    Write-Host "    New project: $ProjectDir"
} else {
    Write-Host "OK  analyseJenkins registered in $PROFILE"
    Write-Host "    Project: $ProjectDir"
}
Write-Host ""
Write-Host "Reload your profile:"
Write-Host "  . `$PROFILE"
Write-Host ""
Write-Host "Then from any directory:"
Write-Host "  analyseJenkins"
