# setup.ps1 — Register the `analyseJenkins` PowerShell command for the
# current user.  Lives under scripts\ in the project root.
#
# Detects the project directory via the current working directory.
# Appends an idempotent function block to $PROFILE (creating it if absent).
# Re-running replaces the previous entry instead of duplicating it.
#
# Usage:
#   Set-Location C:\wherever\you\cloned\Jenkins
#   .\scripts\setup.ps1
#   . $PROFILE          # reload profile
#   analyseJenkins       # works from any directory

$ErrorActionPreference = "Stop"

# ---- 1. Resolve absolute project directory -----------------------------
# Expected: user runs from the project root, e.g. `.\scripts\setup.ps1`.
# Sanity check below catches a wrong-dir run.
$ProjectDir = (Get-Location).Path

if (-not (Test-Path "$ProjectDir\app.py") -or -not (Test-Path "$ProjectDir\config\rules.yaml")) {
    Write-Host "ERROR: this doesn't look like the Jenkins dashboard project root."
    Write-Host "       Current directory: $ProjectDir"
    Write-Host "       Expected: app.py and config\rules.yaml in the current directory."
    Write-Host ""
    Write-Host "Please cd into the project root first, then re-run:"
    Write-Host "  Set-Location C:\path\to\Jenkins"
    Write-Host "  .\scripts\setup.ps1"
    exit 1
}

# ---- 2. Ensure profile path + file exist -------------------------------
if (-not (Test-Path -Path $PROFILE)) {
    New-Item -ItemType File -Path $PROFILE -Force | Out-Null
}

$BeginMark = "# >>> analyseJenkins (managed by scripts\setup.ps1) >>>"
$EndMark   = "# <<< analyseJenkins (managed by scripts\setup.ps1) <<<"

# ---- 3. Build the function block (path baked in) -----------------------
$Block = @"
$BeginMark
# Auto-generated by $ProjectDir\scripts\setup.ps1
# Re-run scripts\setup.ps1 whenever you move or re-clone the project.
function analyseJenkins {
    Push-Location "$ProjectDir"
    try {
        if (-not (Test-Path "venv\Scripts\Activate.ps1")) {
            Write-Host "venv missing — run: py -3 -m venv venv; .\venv\Scripts\Activate.ps1; pip install Flask requests PyYAML"
            return
        }
        & .\venv\Scripts\Activate.ps1
        python app.py
    }
    finally {
        Pop-Location
    }
}
$EndMark
"@

# ---- 4. Idempotent insert: strip existing block, then append -----------
$existing  = Get-Content -Path $PROFILE -Raw -ErrorAction SilentlyContinue
if ($null -eq $existing) { $existing = "" }

# Remove any previously-managed block (current marker).
$pattern   = [regex]::Escape($BeginMark) + "(?s).*?" + [regex]::Escape($EndMark)
$cleaned   = [regex]::Replace($existing, $pattern, "")

# Also strip the legacy marker from before setup\ existed.
$legacyBegin = "# >>> analyseJenkins (managed by setup.ps1) >>>"
$legacyEnd   = "# <<< analyseJenkins (managed by setup.ps1) <<<"
$legacyPattern = [regex]::Escape($legacyBegin) + "(?s).*?" + [regex]::Escape($legacyEnd)
$cleaned   = [regex]::Replace($cleaned, $legacyPattern, "")

# Build the final file content.  Only insert a separator blank line when
# pre-existing user content remains — otherwise a fresh profile would
# start with two blank lines for no reason.
$trimmed = $cleaned.TrimEnd()
if ($trimmed.Length -gt 0) {
    $final = $trimmed + "`r`n`r`n" + $Block + "`r`n"
} else {
    $final = $Block + "`r`n"
}

Set-Content -Path $PROFILE -Value $final -Encoding UTF8

Write-Host "OK  analyseJenkins registered in $PROFILE"
Write-Host "    Project: $ProjectDir"
Write-Host ""
Write-Host "Reload your profile:"
Write-Host "  . `$PROFILE"
Write-Host ""
Write-Host "Then from any directory:"
Write-Host "  analyseJenkins"
