#!/usr/bin/env bash
# setup.sh — Register the `analyseJenkins` shell command for the current
# user.  Lives under scripts/ in the project root.
#
#
# Usage:
#   cd /wherever/you/cloned/Jenkins
#   bash scripts/setup.sh
#   source ~/.zshrc       # (or ~/.bashrc)
#   analyseJenkins         # works from any directory

set -euo pipefail

#  1. Resolve absolute project directory 
# Expected: user runs from the project root, e.g. `bash scripts/setup.sh`.
# Sanity check below catches a wrong-dir run.
PROJECT_DIR="$(pwd)"

if [ ! -f "$PROJECT_DIR/app.py" ] || [ ! -f "$PROJECT_DIR/config/rules.yaml" ]; then
    echo "ERROR: this doesn't look like the Jenkins dashboard project root."
    echo "       Current directory: $PROJECT_DIR"
    echo "       Expected: app.py and config/rules.yaml in the current directory."
    echo ""
    echo "Please cd into the project root first, then re-run:"
    echo "  cd /path/to/Jenkins"
    echo "  bash scripts/setup.sh"
    exit 1
fi

#  2. Pick the rc file matching the user's login shell --
case "${SHELL##*/}" in
    zsh)   RC_FILE="$HOME/.zshrc" ;;
    bash)
        # macOS quirk: Terminal.app / iTerm2 open *login* shells, which
        # read .bash_profile (NOT .bashrc).  Linux distros source .bashrc
        # for interactive shells, so prefer that on non-macOS.
        if [ "$(uname -s)" = "Darwin" ]; then
            RC_FILE="$HOME/.bash_profile"
        else
            RC_FILE="$HOME/.bashrc"
        fi
        ;;
    *)
        echo "Unsupported shell: ${SHELL}.  Add the function manually — see README."
        exit 1
        ;;
esac

BEGIN_MARK="# >>> analyseJenkins (managed by scripts/setup.sh) >>>"
END_MARK="# <<< analyseJenkins (managed by scripts/setup.sh) <<<"

#  3. Build the function block (path baked in for portability) ---
read -r -d '' BLOCK <<EOF || true
${BEGIN_MARK}
# Auto-generated by ${PROJECT_DIR}/scripts/setup.sh
# Re-run scripts/setup.sh whenever you move or re-clone the project.
analyseJenkins() {
    (
        cd "${PROJECT_DIR}" || exit 1
        if [ ! -d venv ]; then
            echo "venv missing — run: python3 -m venv venv && source venv/bin/activate && pip install Flask requests PyYAML"
            exit 1
        fi
        source venv/bin/activate
        python app.py
    )
}
${END_MARK}
EOF

#  4. Idempotent insert: strip any existing block, then append --
mkdir -p "$(dirname "$RC_FILE")"
touch "$RC_FILE"

# Remove any previously-managed block (works on both Linux and macOS sed).
TMP="$(mktemp)"
awk -v b="$BEGIN_MARK" -v e="$END_MARK" '
    $0 == b { skip = 1; next }
    $0 == e { skip = 0; next }
    !skip { print }
' "$RC_FILE" > "$TMP"
mv "$TMP" "$RC_FILE"

# Also strip the legacy marker from before setup/ existed.
LEGACY_BEGIN="# >>> analyseJenkins (managed by setup.sh) >>>"
LEGACY_END="# <<< analyseJenkins (managed by setup.sh) <<<"
TMP="$(mktemp)"
awk -v b="$LEGACY_BEGIN" -v e="$LEGACY_END" '
    $0 == b { skip = 1; next }
    $0 == e { skip = 0; next }
    !skip { print }
' "$RC_FILE" > "$TMP"
mv "$TMP" "$RC_FILE"

# Append the fresh block.
printf '\n%s\n' "$BLOCK" >> "$RC_FILE"

echo "✓ analyseJenkins registered in ${RC_FILE}"
echo "  Project: ${PROJECT_DIR}"
echo ""
echo "Reload your shell:"
echo "  source ${RC_FILE}"
echo ""
echo "Then from any directory:"
echo "  analyseJenkins"
