#!/usr/bin/env bash
# Adds the `analyseJenkins` command to your shell. Runnable from any
# directory — the script locates the project itself. Re-run only if the
# project moves; the script no-ops if the same registration already exists.
#
# Usage:
#   bash /path/to/Jenkins/scripts/setup.sh
#   source ~/.zshrc       # (or ~/.bashrc / ~/.bash_profile)
#   analyseJenkins         # now works from anywhere

set -euo pipefail

# Find the project root from the script's own location.
# Walks any symlink chain so a symlinked setup.sh still resolves correctly.
SCRIPT_PATH="${BASH_SOURCE[0]}"
while [ -L "$SCRIPT_PATH" ]; do
    LINK_TARGET="$(readlink "$SCRIPT_PATH")"
    case "$LINK_TARGET" in
        /*) SCRIPT_PATH="$LINK_TARGET" ;;
        *)  SCRIPT_PATH="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)/$LINK_TARGET" ;;
    esac
done
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Confirm we're actually pointed at the project root.
if [ ! -f "$PROJECT_DIR/app.py" ] || [ ! -d "$PROJECT_DIR/config/rules" ]; then
    echo "ERROR: '$PROJECT_DIR' does not look like the Jenkins dashboard project root."
    echo "       Expected: app.py and config/rules/ at this location."
    echo "       Make sure scripts/setup.sh lives inside the project's scripts/ folder."
    exit 1
fi

# Pick the rc file matching the user's shell.
case "${SHELL##*/}" in
    zsh)   RC_FILE="$HOME/.zshrc" ;;
    bash)
        # macOS terminals open login shells (.bash_profile);
        # Linux distros use .bashrc for interactive shells.
        if [ "$(uname -s)" = "Darwin" ]; then
            RC_FILE="$HOME/.bash_profile"
        else
            RC_FILE="$HOME/.bashrc"
        fi
        ;;
    *)
        echo "Unsupported shell: ${SHELL}.  Add the function manually — see README."
        exit 1
        ;;
esac

BEGIN_MARK="# >>> analyseJenkins (managed by scripts/setup.sh) >>>"
END_MARK="# <<< analyseJenkins (managed by scripts/setup.sh) <<<"

mkdir -p "$(dirname "$RC_FILE")"
touch "$RC_FILE"

# Skip if the same registration is already in place. Pulls the cd-path
# out of any existing block and compares it to the current project root.
EXISTING_DIR=""
if grep -qF "$BEGIN_MARK" "$RC_FILE"; then
    EXISTING_DIR="$(awk -v b="$BEGIN_MARK" -v e="$END_MARK" '
        $0 == b { in_block = 1; next }
        $0 == e { in_block = 0; next }
        in_block && /^[[:space:]]*cd[[:space:]]+"/ {
            sub(/^[[:space:]]*cd[[:space:]]+"/, "")
            sub(/".*/, "")
            print
            exit
        }
    ' "$RC_FILE")"
fi
if [ -n "$EXISTING_DIR" ] && [ "$EXISTING_DIR" = "$PROJECT_DIR" ]; then
    echo "✓ analyseJenkins already registered for this project — nothing to do."
    echo "  Project: ${PROJECT_DIR}"
    echo "  rc file: ${RC_FILE}"
    exit 0
fi

# Function body written into the rc file. PROJECT_DIR is captured here so
# the command keeps working from any directory. 
read -r -d '' BLOCK <<EOF || true
${BEGIN_MARK}
# Auto-generated by ${PROJECT_DIR}/scripts/setup.sh
# Re-run scripts/setup.sh whenever you move or re-clone the project.
analyseJenkins() {
    (
        cd "${PROJECT_DIR}" || exit 1
        # Pick the first venv directory that exists.
        VENV_DIR=""
        for candidate in venv .venv env; do
            if [ -d "\$candidate" ]; then VENV_DIR="\$candidate"; break; fi
        done
        if [ -z "\$VENV_DIR" ]; then
            echo "venv missing — run: python3 -m venv venv && source venv/bin/activate && pip install -r requirements.lock.txt && pip install -e . --no-deps"
            exit 1
        fi
        # shellcheck disable=SC1090
        source "\$VENV_DIR/bin/activate"
        # Use whichever Python is on PATH after activation.
        if   command -v python3 >/dev/null 2>&1; then PYBIN=python3
        elif command -v python  >/dev/null 2>&1; then PYBIN=python
        else echo "No Python on PATH after activating \$VENV_DIR"; exit 1
        fi
        "\$PYBIN" app.py
    )
}
${END_MARK}
EOF

# Safe to re-run: strip any previous block with our marker before appending.
TMP="$(mktemp)"
awk -v b="$BEGIN_MARK" -v e="$END_MARK" '
    $0 == b { skip = 1; next }
    $0 == e { skip = 0; next }
    !skip { print }
' "$RC_FILE" > "$TMP"
mv "$TMP" "$RC_FILE"

# Also clean up the older marker from before the scripts/ folder existed.
LEGACY_BEGIN="# >>> analyseJenkins (managed by setup.sh) >>>"
LEGACY_END="# <<< analyseJenkins (managed by setup.sh) <<<"
TMP="$(mktemp)"
awk -v b="$LEGACY_BEGIN" -v e="$LEGACY_END" '
    $0 == b { skip = 1; next }
    $0 == e { skip = 0; next }
    !skip { print }
' "$RC_FILE" > "$TMP"
mv "$TMP" "$RC_FILE"

printf '\n%s\n' "$BLOCK" >> "$RC_FILE"

if [ -n "$EXISTING_DIR" ]; then
    echo "✓ analyseJenkins re-registered (project moved)."
    echo "  Old project: ${EXISTING_DIR}"
    echo "  New project: ${PROJECT_DIR}"
else
    echo "✓ analyseJenkins registered in ${RC_FILE}"
    echo "  Project: ${PROJECT_DIR}"
fi
echo ""
echo "Reload your shell:"
echo "  source ${RC_FILE}"
echo ""
echo "Then from any directory:"
echo "  analyseJenkins"
